# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/github/pruebas_ipd432/UART_PROFE/UART_PROFE.runs/synth_1/ME_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/github/pruebas_ipd432/UART_PROFE/UART_PROFE.cache/wt [current_project]
set_property parent.project_path E:/github/pruebas_ipd432/UART_PROFE/UART_PROFE.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/github/pruebas_ipd432/UART_PROFE/UART_PROFE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/TX_control.sv
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/TX_sequence.sv
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/UART_tx_control_wrapper.sv
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/pb_debouncer.sv
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/ME_top.sv
}
read_verilog -library xil_defaultlib {
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/bcd_to_ss.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/clk_divider.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/uart/data_sync.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/display_mux.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/uart/uart_basic.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/uart/uart_baud_tick_gen.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/uart/uart_rx.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/uart/uart_tx.v
  E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/sources/new/unsigned_to_bcd.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/constrs/UART_master_const.xdc
set_property used_in_implementation false [get_files E:/github/IPD432/UART_reference_files/UART_ME_reference/UART_master.srcs/constrs/UART_master_const.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ME_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ME_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file ME_top_utilization_synth.rpt -pb ME_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
