# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/tarea2/source_files/UART_master_const.xdc

# IP: D:/tarea2/source_files/ip/blk_mem_gen_ff/blk_mem_gen_ff.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_ff || ORIG_REF_NAME==blk_mem_gen_ff} -quiet] -quiet

# IP: D:/tarea2/source_files/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
