# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/github/pruebas_ipd432/TAREA_2_UART/UART_master_const.xdc

# IP: ip/ila_0/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet
